apiVersion: v2
name: compliance-toolkit-batch-job
description: A Helm chart for MOSIP compliance toolkit batchjob service
type: application
version: 1.0.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - compliance-toolkit-batch-job
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
